# Generated by Django 2.2.3 on 2019-08-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_history_historyitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='items', to='item.Category'),
        ),
    ]
